const { model, Schema } = require("mongoose");

const statementDetailSchema = new Schema({
  firstName: String,
  lastName: String,
  accountNumber: String,
  date: String,
  consumerName: String,
  phoneNumber: String,
  email: String,
  password: String,
  idNumber: String,
  isIndigent: String,
  indigentExpiry: String,
  indigentApplicationDate: String,
  lastPaymentDate: String,
  lastPaymentAmount: String,
  accountStatus: String,
  province: String,
  town: String,
  suburb: String,
  ward: String,
  street: String,
  postalAddress1: String,
  postalAddress2: String,
  postalAddress3: String,
  postalCode: String,
  vatNumber: String,
  deposit: String,
  marketValue: String,
  erfNumber: String,
  taxNumber: String,
  days120: Number,
  days90: Number,
  days60: Number,
  days30: Number,
  current: Number,
  closingBalance: String,
  openingBalance: String,
  createdAt: String,
});

module.exports = model("StatementDetail", statementDetailSchema);
